#!/usr/bin/with-contenv bash

umask 022

IFS=" " read -r -a RUN_ARRAY <<< "$RUN_OPTS"

mount_command="plexdrive mount -c /config/ --cache-file=/config/cache.bolt --uid=$PUID --gid=$PGID -o allow_other /data ${RUN_ARRAY[@]}"

echo "Executing => $mount_command"
exec \
	s6-setuidgid abc $mount_command
