#!/usr/bin/with-contenv bash

pd_mountpoint=$(if ! mountpoint -q /local; then echo /data; else echo /cloud; fi)

pd_basic_opts="
-c /config/
--cache-file=/cache/cache.bolt
--uid=${PUID:-911}
--gid=${PGID:-911}
--umask=0100775
-o allow_other
"

IFS=" " read -r -a pd_user_opts <<< "$PLEXDRIVE_OPTS"

mount_command="plexdrive mount ${pd_mountpoint} $(echo $pd_basic_opts) ${pd_user_opts[@]}"
echo "executing => $mount_command"
exec s6-setuidgid abc $mount_command
