#!/usr/bin/with-contenv bash

umask 022

mongodb_command="mongod --dbpath=/mongo/db --logpath=/mongo/logs/mongod.log --logappend --logRotate=reopen --bind_ip=127.0.0.1"

echo "Executing => $mongodb_command"
exec \
	s6-setuidgid abc $mongodb_command
