#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config /data /chunks /mongo/{db,logs} /plexdrive

# permissions
chown -R abc:abc /config /data /chunks /mongo /plexdrive
chmod a+x /usr/bin/{plexdrive_setup,ufs}
