#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

echo "*** checking config"
while [ ! -f "/config/config.json" ] || [ ! -f "/config/token.json" ]; do
    echo "Waiting for config files in /config. Retrying in 30s ..."
    echo "RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup"
    sleep 30
done

echo "*** checking mountpoint: ${pd_mountpoint}"
while findmnt "${pd_mountpoint}" | grep -q fuse; do
    echo "ERROR: mountpoint (${pd_mountpoint}) already mounted"
    fusermount -uz "${pd_mountpoint}"
    echo "Retrying in 15s ..."
    sleep 15
done

# permissions
chown -R abc:abc \
    /config /cloud /data /cache
chown abc:abc /local

# display version
echo "*** plexdrive $(plexdrive --version) ready!"
